name: Deploy to cPanel

on:
  push:
    branches:
      - Production

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Deploy to cPanel via SFTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.CPANEL_HOST }}
          username: ${{ secrets.CPANEL_USER }}
          password: ${{ secrets.CPANEL_PASSWORD }}
          protocol: ftps
          local-dir: ./
          server-dir: /public_html/branding/
          exclude: |
            **/.git*
            **/node_modules/**
            */config.php**
            config.php
            */*/config.php**
